stacks/java-openliberty/devfile.yaml, stacks/nodejs/devfile.yaml
This PR implements the discussion https://github.com/devfile/api/pull/282#discussion_r552151109, which removes the unnecessary fields that are copies from odo registry repo in stack devfile.
Signed-off-by: jingfu wang <jingfu.j.wang@ibm.com>
=> Remove unnecessary fields in stack devfile

stacks/java-maven/devfile.yaml, stacks/java-maven/meta.yaml, stacks/java-openliberty/devfile.yaml, stacks/java-openliberty/meta.yaml, stacks/java-quarkus/devfile.yaml, stacks/java-quarkus/meta.yaml, stacks/java-springboot/devfile.yaml, stacks/java-springboot/meta.yaml, stacks/java-vertx/devfile.yaml, stacks/java-vertx/meta.yaml, stacks/nodejs/devfile.yaml, stacks/nodejs/meta.yaml, stacks/python-django/devfile.yaml, stacks/python-django/meta.yaml, stacks/python/devfile.yaml, stacks/python/meta.yaml
Signed-off-by: jingfu wang <jingfwan@redhat.com>
This PR merges meta.yaml to devfile.yaml
Related issue: https://github.com/devfile/api/issues/222
=> Merge meta.yaml

stacks/java-maven/devfile.yaml, stacks/java-openliberty/devfile.yaml, stacks/java-wildfly-bootable-jar/devfile.yaml, stacks/java-wildfly/devfile.yaml, stacks/nodejs/devfile.yaml
Updates the devfiles in this registry from odo-devfiles/registry
=> Update devfiles from odo-devfiles/registry

stacks/java-quarkus/devfile.yaml, stacks/java-vertx/devfile.yaml
Updates java-quarkus and java-vertx devfiles based on recent changes in odo-devfiles/registry
=> Update devfiles based on odo-devfiles/registry

stacks/java-openliberty/devfile.yaml
Porting PR: https://github.com/odo-devfiles/registry/pull/77
FYI @ajm01, @scottkurz, @elsony
=> Update the Open Liberty devfile to version 0.4.3

stacks/java-wildfly/devfile.yaml
* Updating the QS version
* Fixing the WildFly image version to be compatible with the QS
=> Fixing WildFly issue while waiting for fix in WildFly 23.0.1 image

stacks/java-wildfly-bootable-jar/devfile.yaml, stacks/java-wildfly/devfile.yaml
Signed-off-by: eyuen <eyuen@redhat.com>
=> Updating WildFly the 23 release.

extraDevfileEntries.yaml
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>
Update some typos
=> Update extra devfile typo

stacks/java-quarkus/devfile.yaml
just quarkus as no diff from this and rhbq when it comes to the starters.
=> dont mention upstream quarkus

stacks/nodejs/devfile.yaml
Nodejs stack version should be 14 and not 12.
=> Fixed typo in nodejs stack devfile

stacks/nodejs/devfile.yaml
Small nit PR to match [Node.js brand guidelines](https://nodejs.org/static/documents/trademark-policy.pdf).
I'm not sure if it would be possible to update the tags (and to include `.` in tags), so I've left those as they are for now.
=> Update Node.js DevFile to match brand guidelines

stacks/java-openliberty/devfile.yaml
Signed-off-by: Scott Kurz <skurz@us.ibm.com>
=> Add Java/Maven tags to java-openliberty

.ci/deploy/devfile-registry.yaml
Use health endpoint for readiness probes
=> Use health endpoint for readiness probes

stacks/java-openliberty/devfile.yaml
=> java-openliberty stack devfile updates

.ci/deploy/devfile-registry.yaml, .ci/deploy/route.yaml, .ci/openshift_integration.sh
This PR adds the environment variables to devfile community registry
Signed-off-by: Jingfu Wang <jingfwan@redhat.com>
=> Add environment variables for telemetry

stacks/java-openliberty-gradle/devfile.yaml
=> Add Open Liberty stack devfile that uses Gradle

extraDevfileEntries.yaml
Signed-off-by: eyuen <eyuen@redhat.com>
=> Update samples to non-private repos

stacks/java-maven/devfile.yaml, stacks/python/devfile.yaml
Update python and java maven logos
=> Update python and java maven logos

.github/workflows/trigger-redeploy.yaml
Fixes https://github.com/devfile/api/issues/527
Adds a workflow to receive repository dispatches that will trigger deploys to staging
=> Add workflow for triggering deploys to staging

.ci/openshift_integration.sh, tests/test.sh
The tests on openshift ci need to pass in the path of yq.
=> Pass in yq path to test script

stacks/java-wildfly-bootable-jar/devfile.yaml, stacks/java-wildfly/devfile.yaml
Upgrade WildFly stacks to 25.0
=> Updating WildFly to 25.0.Final

.ci/deploy/devfile-registry.yaml
Enables telemetry for the registry viewer
=> Enable viewer telemetry

extraDevfileEntries.yaml
This PR updates the  extraDevfileEntries.yaml to include provider information in samples index, for ocd to get and show in their frontend
part of https://github.com/devfile/api/issues/658
=> add provider information in samples index

README.md, TELEMETRY.md
Adds a devfile registry telemetry collection notice
https://github.com/devfile/api/issues/673
=> Add telemetry collection notice

CONTRIBUTING.md
Update CONTRIBUTING.md with the instructions to test stacks and samples with online Che (workspaces.openshift.com).
N/A
=> Add instructions to "test with Che" in the registry contributing guide

stacks/java-openliberty-gradle/devfile.yaml, stacks/java-websphereliberty-gradle/devfile.yaml, stacks/java-websphereliberty/devfile.yaml
Existing stack updated:
- java-openliberty
- java-openliberty-gradle
Updates:
Adding the use of variables, update image used, and command execution updates
New devfiles being added:
- java-websphereliberty
- java-websphereliberty-gradle
No issue.
=> Update Liberty stack devfiles

.github/workflows/validate-devfiles-minikube.yaml
Runs the Devfile MiniKube tests in a CronJob that runs every day at [Midnight (5 am UTC)](https://crontab.guru/#0_5_*_*_*)
[_Link to github issue(s)_](https://github.com/devfile/api/issues/759)
N/A
N/A
=> Run MiniKube tests in a CronJob

stacks/nodejs-angular/devfile.yaml, stacks/nodejs-nextjs/devfile.yaml, stacks/nodejs-nuxtjs/devfile.yaml, stacks/nodejs-react/devfile.yaml, stacks/nodejs-svelte/devfile.yaml, stacks/nodejs-vue/devfile.yaml
Updates node stacks to use dev
N/A
=> Updates node stacks to use dev

stacks/python-django/devfile.yaml, stacks/python/devfile.yaml
fixes https://github.com/devfile/api/issues/777
=> python: add missing workingDir

stacks/java-wildfly-bootable-jar/devfile.yaml, stacks/java-wildfly/devfile.yaml
Upgrading the devFile to latest WildFly release
=> Upgrading to WildFly 26.1

.ci/acceptance-tests/devfile-registry-acceptance.yaml
The acceptance tests job needs a service account too
=> Add service account for acceptance tests

.ci/Dockerfile, .ci/build.sh, .ci/build_and_deploy.sh, .ci/deploy/devfile-registry.yaml, .ci/deploy/route.yaml, .ci/openshift_integration.sh, .github/workflows/check-architectures.yaml, .github/workflows/ci.yaml, .github/workflows/comment-pr.yaml, .github/workflows/pushimge-next.yaml, .github/workflows/trigger-redeploy.yaml, .github/workflows/validate-devfiles-minikube.yaml
Signed-off-by: Kim Tsao <ktsao@redhat.com>
updates license headers in a number of files
https://github.com/devfile/api/issues/863
=> registry license updates

extraDevfileEntries.yaml, stacks/python/devfile.yaml
Signed-off-by: Paul Schultz <pschultz@pobox.com>
Updates the python stack/sample icons
N/A
=> Updated the python stack/sample icons

stacks/java-websphereliberty-gradle/devfile.yaml, stacks/java-websphereliberty/devfile.yaml
Signed-off-by: Adam Wisniewski <awisniew@us.ibm.com>
Update the WebSphere Liberty stack logos
N/A
=> Update WebSphere Liberty logos

.ci/deploy/devfile-registry.yaml
Signed-off-by: Kim Tsao <ktsao@redhat.com>
Removes telemetry configs from the staging server
https://github.com/devfile/api/issues/932
=> Remove telemetry from staging server

stacks/nodejs-angular/devfile.yaml
This updates the angular tags to match the other node.js devfiles.
N/A
=> Update anglular tags

README.md
Fixed registry status in README
N/A
=> Fix registry status in README

stacks/go/devfile.yaml
Updates the go image to go-toolset to fix vulnerabilities. 
fixes https://github.com/devfile/api/issues/990
=> Updated go image to go-toolset

stacks/go/devfile.yaml
Changed GOPATH to fix permissions
Fixes https://github.com/devfile/api/issues/994
=> Changed GOPATH to fix permissions

stacks/php-laravel/devfile.yaml, stacks/python/3.0.0/docker/Dockerfile
Signed-off-by: Paul Schultz <pschultz@pobox.com>
Updates composer to the latest image
https://github.com/devfile/api/issues/997
=> Updated composer image

stacks/java-springboot/2.0.0/kubernetes/deploy.yaml, stacks/python/3.0.0/kubernetes/deploy.yaml
Signed-off-by: Michael Hoang <mhoang@redhat.com>
Fixes indentation for the service definition
https://github.com/devfile/api/issues/999
=> fixing service definition whitespace

extraDevfileEntries.yaml, stacks/java-springboot/1.2.0/devfile.yaml, stacks/java-springboot/2.0.0/devfile.yaml
This PR revert back the tag change to Spring boot stacks & samples. 
Alizer expect the tag to be `Spring` to match for devfile. 
https://issues.redhat.com/browse/DEVHAS-219
=> revert back spring tag change

.ci/deploy/devfile-registry.yaml
Signed-off-by: Michael Valdron <mvaldron@redhat.com>
Provides required fixes to setting environment variables on the registry viewer deployment within the OpenShift template. 
fixes devfile/api#1016
=> Fix environment variable definitions for registry viewer deployment

extraDevfileEntries.yaml, stacks/java-springboot/1.2.0/devfile.yaml, stacks/java-springboot/2.0.0/devfile.yaml, stacks/java-springboot/stack.yaml
Signed-off-by: Michael Hoang <mhoang@redhat.com>
https://github.com/devfile/api/issues/1023
=> updating spring icon

CONTRIBUTING.md
This PR updates the contributing guide with odo v3 info. 
https://github.com/devfile/api/issues/1053
=> update with odo v3 info

stacks/go/1.0.2/devfile.yaml, stacks/go/2.0.0/devfile.yaml, stacks/python-django/devfile.yaml, stacks/python/2.1.0/devfile.yaml, stacks/python/3.0.0/devfile.yaml
Updated python and django stack and set up a specific tag (ubi/python:1-108) instead of "latest".
=> Devtools week: Set a specific image tag on Python stacks

stacks/go/1.1.0/devfile.yaml, stacks/go/2.1.0/devfile.yaml, stacks/go/2.1.0/docker/Dockerfile, stacks/go/2.1.0/kubernetes/deploy.yaml, stacks/go/stack.yaml
This adds a missing `debug` command to the Go stack.
&mdash;
Checked with `odo`.
Running `odo dev --debug` and attaching a remote debugger to the local port forwarded by odo should work:
=> [go] Add debug command to Devfile

extraDevfileEntries.yaml
The sample is using OpenJDK 17 now
=> Update Quarkus Sample Description

stacks/nodejs-angular/2.0.2/devfile.yaml, stacks/nodejs-angular/2.1.0/devfile.yaml, stacks/nodejs-angular/2.2.0/devfile.yaml, stacks/nodejs-angular/stack.yaml, stacks/nodejs-nextjs/1.0.3/devfile.yaml, stacks/nodejs-nextjs/1.1.0/devfile.yaml, stacks/nodejs-nextjs/1.2.0/devfile.yaml, stacks/nodejs-nextjs/stack.yaml, stacks/nodejs-nuxtjs/1.0.3/devfile.yaml, stacks/nodejs-nuxtjs/1.1.0/devfile.yaml, stacks/nodejs-nuxtjs/1.2.0/devfile.yaml, stacks/nodejs-nuxtjs/stack.yaml, stacks/nodejs-react/2.0.2/devfile.yaml, stacks/nodejs-react/2.1.0/devfile.yaml, stacks/nodejs-react/2.2.0/devfile.yaml, stacks/nodejs-react/stack.yaml, stacks/nodejs-svelte/1.0.3/devfile.yaml, stacks/nodejs-svelte/1.1.0/devfile.yaml, stacks/nodejs-svelte/1.2.0/devfile.yaml, stacks/nodejs-svelte/stack.yaml, stacks/nodejs-vue/1.0.2/devfile.yaml, stacks/nodejs-vue/1.1.0/devfile.yaml, stacks/nodejs-vue/1.2.0/devfile.yaml, stacks/nodejs-vue/stack.yaml
These changes updates the image tags of the following nodejs stacks:
- [nodejs-angular](https://github.com/michael-valdron/devfile-registry/tree/9aeb6f466ac2d95d590e3819eb95da2db7a659aa/stacks/nodejs-angular)
- [nodejs-nextjs](https://github.com/michael-valdron/devfile-registry/tree/9aeb6f466ac2d95d590e3819eb95da2db7a659aa/stacks/nodejs-nextjs)
- [nodejs-nuxtjs](https://github.com/michael-valdron/devfile-registry/tree/9aeb6f466ac2d95d590e3819eb95da2db7a659aa/stacks/nodejs-nuxtjs)
- [nodejs-react](https://github.com/michael-valdron/devfile-registry/tree/9aeb6f466ac2d95d590e3819eb95da2db7a659aa/stacks/nodejs-react)
- [nodejs-svelte](https://github.com/michael-valdron/devfile-registry/tree/9aeb6f466ac2d95d590e3819eb95da2db7a …
=> [Devtools week] nodejs stacks image tag updates

stacks/go/1.0.2/devfile.yaml, stacks/go/1.1.0/devfile.yaml, stacks/go/2.0.0/devfile.yaml, stacks/go/2.0.0/docker/Dockerfile, stacks/go/2.1.0/devfile.yaml, stacks/go/2.1.0/docker/Dockerfile, stacks/php-laravel/1.0.1/devfile.yaml, stacks/php-laravel/2.0.0/devfile.yaml, stacks/php-laravel/stack.yaml
This PR provides the following changes to each of the go and php-laravel stack versions:
- Updates go stack image tag for the container component from `1.18.9-14` to  `1.18.10-4`
- **Due to an unknown bug within the `ubi9/go-toolset:1.19.9-3` base image experienced with the [basic go sample update](https://github.com/devfile-samples/devfile-sample-go-basic/pull/24), the image tag will only updated to the latest version of go 1.18**
- **It is expected that this image tag will be updated to go 1.19 in the near future**
- Updates go stack image tag within the resource `Dockerfile` to the matching `1.18.10-4` from the invalid `latest` tag
- Fixes a permissions error experienced during the `image-build` command by using the …
=> [Devtools week] go and php-laravel stack image tag updates and fixes

stacks/java-wildfly/stack.yaml
Changes the name field under the java wildfly [stack file](https://github.com/devfile/registry/blob/8402bf1cef04fd10c76c70e8637d3577732406b1/stacks/java-wildfly/stack.yaml#L1) from `ava-wildfly` to `java-wildfly`.
fixes devfile/api#1183
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test …
=> Fix java wildfly stack

.github/workflows/check-architectures.yaml, .github/workflows/ci.yaml, .github/workflows/comment-pr.yaml, .github/workflows/pushimge-next.yaml, .github/workflows/trigger-redeploy.yaml, .github/workflows/validate-stacks.yaml
This PR updates all deprecated github actions using NodeJS 12 in order to use NodeJS 16. The list of actions updated are:
[Active Workflows]
- `actions/checkout@v2` > `actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3`
- `actions/setup-go@v2` > `actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0`
- `docker/login-action@v1` > `docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0`
[Manually disabled workflows -> check-architectures & comment-pr]
- `technote-space/get-diff-action@v4` > `technote-space/get-diff-action@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1`
- `peter-evans/find-comment@v1` > `peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1 # v2.4.0`
- `actions/upload-artifact@v2` > …
=> Update github actions to use NodeJS 16

OWNERS
Updates the OWNERS file by including all devfile team members
This task is part of devtools week sep 2023
=> [Devtools Week] Update OWNERS file

tests/rhtap/rhtap_test.go
=> Upgrade timeout of deleted applications

.gitignore, tests/rhtap/rhtap_test.go
=> Assign a rhtap namespace for every devfile to avoid ArgoCD when delete applications

.gitignore, tests/rhtap/rhtap_test.go
=> [rhtap-e2e]: Remove components and application from test namespace

tests/rhtap/rhtap_test.go
=> Do not remove namespace for debug utilities

README.md, renovate.json
Renovate to consume platform engineering global configuration
=> Renovate - consume PE global configuration

OWNERS
Needed for self servicing openshift ci changes
=> Add back myself to OWNERS

.github/workflows/pushimge-next.yaml
Reverts devfile/registry#330 due to failing quay.io login after changes.
=> Revert "chore(deps): update docker/login-action to v3.1.0"

stacks/java-openliberty/devfile.yaml
This PR updates the java-openliberty sample:
1. Update schemaversion to 2.2.2
2. Update endpoint protocol to https
=> Update java-openliberty devfile

stacks/java-openliberty-gradle/devfile.yaml
This PR updates the java-openliberty-gradle sample:
1. Update schemaversion to 2.2.2
2. Update endpoint protocol to https
=> Update java-openliberty-gradle devfile

stacks/nodejs-vue/1.2.1/devfile.yaml, stacks/nodejs-vue/stack.yaml
Add a new version and set https endpoint to NodeJs-Vue stack.
https://github.com/eclipse-che/che/issues/22869
=> Add new version and set https endpoint to nodejs-vue

stacks/ollama/OWNERS, stacks/ollama/devfile.yaml
Adding Ollama devfile
Inspired by https://www.opensourcerers.org/2023/11/06/a-personal-ai-assistant-for-developers-that-doesnt-phone-home/
https://issues.redhat.com/browse/CRW-6049
https://workspaces.openshift.com#https://raw.githubusercontent.com/devfile/registry/b0af3873840501ae8732c997bc528dfcb011c879/stacks/ollama/devfi …
=> Adding Ollama devfile

stacks/ollama/OWNERS
chore: Update ollama OWNERS (adding 'manhah')
@manhah is the original author of the https://www.opensourcerers.org/2023/11/06/a-personal-ai-assistant-for-developers-that-doesnt-phone-home/ and I would like to have him as the owner of the devfile
=> chore: Update ollama OWNERS (adding 'manhah')

stacks/go/2.4.0/devfile.yaml, stacks/go/2.4.0/docker/Dockerfile, stacks/go/2.4.0/kubernetes/deploy.yaml, stacks/go/stack.yaml
Adding go 1.21 devfile
N/A
https://workspaces.openshift.com#https://raw.githubusercontent.com/devfile/registry/747c75aeefb71de0f154c77cf307940a9b7069c1/stacks/go/2.4.0/devfile.yaml
=> Adding go 1.21 devfile

CONTRIBUTING.md, DCO, README.md
Updates contributing guide and supporting documents with up to date information and layout.
Additionally, adds missing `DCO` file into repository.
fixes devfile/api#1347
=> Update contributing guide

.ci/Dockerfile, .ci/Dockerfile.offline, .ci/generate_last_mod_file.sh
This PR adds a new script for generating the last modified dates for each stack and sample in the registry. This script compiles data about each stack and sample and their last modified date into a `last_modified.json` file that is intended to be passed to the index/generator for reference. 
An example of the `last_modified.json` contents:
```
{
"stacks": [
{
"stack": "go",
"version": "1.2.0",
"last_modified": "2023-11-08T12:54:08+00:00"
},
{
"stack": "go",
"version": "1.2.1",
"last_modified": "2024-04-19T12:47:24+02:00"
},
{
"stack": "go",
"version": "1.3.0",
"last_modified": "2024-04-29T12:02:57+02:00"
},
{
"stack": "go",
"version": "1.3.1",
"last_modified": "2024-04-29T12:02:57+02:00"
},
{
"stack": "go",
"version": …
```
=> Add new script for generating the last modified dates of stacks and samples

stacks/java-springboot/1.3.0/devfile.yaml, stacks/java-springboot/1.4.0/devfile.yaml, stacks/java-springboot/2.1.0/devfile.yaml, stacks/java-springboot/2.2.0/devfile.yaml
=> Fix description for Java SpringBoot stack when using JDK 17 and not JDK 11

stacks/jhipster-online/2.33.0/devfile.yaml, stacks/jhipster-online/stack.yaml
Updates the description of the JHipster devfile
N/A
_Explain what tests you personally ran to ensure the changes are functioning as expected._
_Instructions for the reviewer on how to test your …
=> Update jhipster-online description

.tekton/devfile-registry-main-pull-request.yaml, .tekton/devfile-registry-main-push.yaml
Patches konflux pipeline task images to fix ec testing failures.
part of devfile/api#1667
_Explain what tests you personally ran to ensure the changes are functioning as expected._
_Instructions …
=> chore(deps): patch konflux pipeline task images
