devfile/registry

.github/workflows/pushimge-next.yaml
Signed-off-by: jingfu wang <jingfwan@redhat.com>
This PR adds the repository dispatch in github CI on the receiver side.
PR to send the repository dispatch event: https://github.com/devfile/registry-support/pull/26
=> Add repository dispatch

.ci/build.sh, .ci/build_and_deploy.sh
The cicd pipeline job for the hosted devfile registry requires there be scripts in this repository that can build the registry into the devfile index image and push it to quay.io/app-sre. So I've added a couple simple scripts that do the following:
1) a build.sh script that clones the registry builds tools and calls the registry build script
2) a build_and_deploy.sh script that calls the aforementioned build.sh script and pushes it up to the quay.io/app-sre repo.
Signed-off-by: John Collier <jcollier@redhat.com>
=> (Hosted Registry) Set up cicd scripts for the hosted registry

.ci/build_and_deploy.sh
This PR updates the build_and_deploy.sh script that runs on the app-sre jenkins CI job to properly set the `IMAGE` and `IMAGE_TAG` variables. It also makes sure now to push to both to the given tag (corresponding to the git revision) as well as the `next` tag.
=> Set environment variables for pushing index image to quay

stacks/java-openliberty/devfile.yaml
The java-openliberty devfile was updated on the odo-devfiles/registry repo shortly after the last registry sync that I did, so I'm just updating it here.
=> Updata java-openliberty from odo-devfiles

stacks/java-openliberty/devfile.yaml
FYI @scottkurz, @elsony
A similar PR was submitted to the odo-devfiles repo: https://github.com/odo-devfiles/registry/pull/78
=> Update Open Liberty devifle to version 0.5.0

.ci/build.sh
I'm going to be delivering some breaking changes to the build tools in https://github.com/devfile/registry-support/tree/master/build-tools and I don't want to break the scripts in this repository that depend on them, so hardcoding to a specific commit in the meanwhile.
=> Hard code scripts to specific commit of build tools

extraDevfileEntries.yaml
This PR adds extraDevfileEntires.yaml to support sample according to the proposal: https://docs.google.com/document/d/1tbzZK9aWtpw5AtoZmUl1Jy8x8w9N5hhjXu3c26VYiYY/edit#heading=h.6w072oor8mro
Signed-off-by: jingfu wang <jingfwan@redhat.com>
=> Add extraDevfileEntires.yaml to support sample

.ci/build.sh, .github/workflows/ci.yaml, .github/workflows/pushimge-next.yaml
We should be calling `build_image.sh` in the Github actions for this repo now rather than `build.sh`
=> Fix GitHub actions for updated build tools

.ci/Dockerfile
AppSRE's ci-int pipelines requires the images used in Dockerfiles to be in quay.io, so moving to an alpine-go base image hosted on quay.
=> Use quay.io alpine-go image for registry build layer

.ci/openshift_integration.sh
We need to make sure we're running the tests in their own dedicated namespace in the OpenShift CI
CC @josephca
=> Run tests in dedicated project

.ci/openshift_integration.sh
Looks like permissions in the CI test container isn't sufficient to use the default odo preferences file, so need to override the location.
=> Update CI test script to use local preferences file

.dockerignore
The index server's endpoints now properly supports samples, so we can update the registry to remove the .dockerignore file that was preventing the extraDevfilesEntry yaml file from being included in the registry build
=> Remove dockerignore file for extraDevfilesEntry

extraDevfileEntries.yaml
Given we only store the sample metadata in the registry instead of storing all the sample resource, then in the icon field of the sample metadata we should use the full icon URL instead of file path as we don't store the icon in our registry.
Signed-off-by: Jingfu Wang <jingfwan@redhat.com>
=> Update sample icon link

.ci/acceptance-tests/devfile-registry-acceptance.yaml
Migrates the acceptance tests templates from registry-support to this repository as AppSRE requires it to be in this repo.
=> Migrate devfile-registry acceptance tests

.ci/deploy/devfile-registry.yaml
AppSRE's tekton based pipelines now require that the OpenShift templates for the devfile registry be hosted in this repository, so migrating the OpenShift template from registry-support to this repo.
=> Migrate openshift template for registry

extraDevfileEntries.yaml
I've created a Node.js DevFile Sample that the Node.js team will maintain at https://github.com/nodeshift-starters/devfile-sample. We'd like to control the content of the Node.js sample so it can be aligned with our [reference architecture for Node.js](https://github.com/nodeshift/nodejs-reference-architecture).
I do not know how to test that the DevFile Sample we've created conforms to the expected specification to enable it to be shown as a sample in the DevFile UI. I tried to infer what was necessary from https://github.com/redhat-developer/devfile-sample (e.g. `Dockerfile`, and `alpha.build-dockerfile: Dockerfile` attributes in the DevFile).
- https://github.com/nodeshift-starters/devfile-sample/blob/main/devfile.yaml
- https://github.com/nodeshift-starters/devfile-sample/blob/main/Doc …
=> sample: point to new Node.js DevFile sample

.ci/Dockerfile
The updated build tools now require yq, so updated the dockerfile to add it. 
The index server base image now expects the stacks and samples to be under `/registry` so updating the dockerfile for that too.
=> Update dockerfile to use yq

.ci/build.sh
The Jenkins build for the registry on AppSRE seems to be stuck using a cached version of the devfile index base image, so adding this flag to disable it.
=> Disable layer caching on image build for registry

.github/workflows/ci.yaml, .github/workflows/validate-devfiles-minikube.yaml
Fixes https://github.com/devfile/api/issues/525
- Updates the registry test action to use an updated version of `manusa/actions-setup-minikube`, as well as a newer version of Kubernetes.
- Removes an unnecessary checkout of the registry-support repo during the CI build, it's no longer needed.
=> Update Minikube action to newer version

stacks/java-vertx/devfile.yaml
Adds an icon for the java-vertx stack:
Sourced from: https://github.com/vertx-web-site/vertx-logo/blob/master/vertx-logo.svg
=> Add icon for java-vertx stack

stacks/java-springboot/devfile.yaml, stacks/python-django/devfile.yaml, stacks/python/devfile.yaml
Adds icons for the following stacks:
- `java-springboot`: https://spring.io/images/projects/spring-edf462fec682b9d48cf628eaf9e19521.svg
- `python`: https://www.python.org/static/community_logos/python-logo-generic.svg
- `python-django`: https://static.djangoproject.com/img/logos/django-logo-positive.svg
=> Add icons for springboot, python, python-django

stacks/java-openliberty/devfile.yaml
Adds an icon for the java-openliberty stack:
Sourced from https://raw.githubusercontent.com/OpenLiberty/logos/7fbb132949b9b2589e18c8d5665c1b107028a21d/logomark/svg/OL_logomark.svg
@scottkurz @mezarin Let me know if this is the right icon to use or if another should be used.
=> Add icon for Open Liberty

stacks/nodejs/devfile.yaml
Adds an icon for the nodejs stack:
Sourced from https://nodejs.org/static/images/logos/nodejs-new-pantone-black.svg
=> Add icon for nodejs stack

stacks/java-wildfly-bootable-jar/devfile.yaml, stacks/java-wildfly/devfile.yaml
Adds icons for the two wildfly stacks (java-wildfly and java-wildfly-bootable-jar):
Sourced from: https://design.jboss.org/wildfly/logo/final/wildfly_logomark.svg
=> Add icons for wildfly stacks

stacks/java-quarkus/devfile.yaml
Adds an icon for the java-quarkus stack:
Sourced from: https://design.jboss.org/quarkus/logo/final/SVG/quarkus_icon_rgb_default.svg
=> Add icon for java-quarkus stack

.ci/deploy/devfile-registry.yaml
**DO NOT MERGE UNTIL https://github.com/devfile/registry-support/pull/73 IS MERGED**
- Adds the viewer host config to the registry configmap
- Updates the resources for the index server container accordingly (higher resources needed to accommodate the viewer)
- Adds a startup probe to trigger the regeneration of the viewer
=> Update OpenShift template for registry viewer

extraDevfileEntries.yaml
Uses the same svg icons for samples that we used for their equivalent stacks (nodejs, quarkus, java-springboot, python)
=> Use svg icons for samples

.ci/deploy/devfile-registry.yaml, .ci/openshift_integration.sh
AppSRE's tekton pipelines need to use IMAGE_TAG for the registry's openshift template.
I'm leaving in the old parameter until I update the saas-file in app interface to not mention the parameter.
=> Use IMAGE_TAG instead of DEVFILE_INDEX_IMAGE_TAG for parameter

.github/workflows/trigger-redeploy.yaml
Need to set `persist-credentials: false` in order to be able to make the dummy commit when dispatches are received.
=> Use persist-credentials: false in deploy trigger

.ci/openshift_integration.sh, tests/test.sh
New version of odo requires that we change the following in the tests:
- Don't pass in devfile name when testing devfiles locally
- Must pass in the starter project name now
=> Update tests for new odo version

.ci/deploy/devfile-registry.yaml, stacks/nodejs-angular/devfile.yaml, stacks/nodejs-nextjs/devfile.yaml, stacks/nodejs-nuxtjs/devfile.yaml, stacks/nodejs-react/devfile.yaml, stacks/nodejs-svelte/devfile.yaml, stacks/nodejs-vue/devfile.yaml, tests/test.sh
Adds an env variable to the OpenShift template that sets the `alias` field in the registry viewer's config.
Also adds a small, unrelated change to the test script that makes sure we call `odo delete` when `odo push` fails.
=> Add viewer host alias

.ci/deploy/devfile-registry.yaml
Need to add curly brackets around the env var so that AppSRE's tekton pipelines can properly set the variable.
=> Fix openshift template

stacks/dotnet50/devfile.yaml, stacks/dotnetcore31/devfile.yaml
.NET doesn't allow the build to overwrite the files that the running
application is using.
Before starting the build, kill the 'dotnet run' process.
And, add 'UseSharedCompilation=false' to avoid 'dotnet' build processes
that stick around after the 'dotnet build'.
@kadel ptal.
=> dotnet: fix build failing due to running application.

stacks/dotnet60/devfile.yaml
Adds a stack for .NET 6.0 which will be released this week.
This is a copy of the `dotnet50` stack with `5` replaced by `6` in the devfile.
@kadel @johnmcollier ptal.
=> Add dotnet60 stack

stacks/php-laravel/devfile.yaml
Downgraded Composer to composer:2.1.11 since Laravel only supports PHP 8.0
Fixes https://github.com/devfile/api/issues/701
N/A
=> Fixes Laravel stack

stacks/java-openliberty-gradle/devfile.yaml, stacks/java-openliberty/devfile.yaml, stacks/java-websphereliberty-gradle/devfile.yaml, stacks/java-websphereliberty/devfile.yaml
Signed-off-by: Andrew Mauer <ajmauer@gmail.com>
Existing stacks updated:
- java-openliberty
- java-openliberty-gradle
- java-websphereliberty
- java-websphereliberty-gradle
Updates:
- devfile variable to allow config of what mvn and gradle commands are used
- devfile component container memoryLimit value was updated.
- app-deploy.yaml is now compatible with Open Liberty Operator version 0.8.0
- updated liberty images used in each of the stacks
https://github.com/OpenLiberty/devfile-stack/issues/185
https://github.com/OpenLiberty/devfile-stack/issues/197
_All javaliberty and websphereliberty testcases pass_
_No doc update needed_
=> Jan 2022 updates to open-liberty and websphere-liberty stacks

.ci/openshift_integration.sh, stacks/python-django/devfile.yaml, stacks/python/devfile.yaml
Updates the OpenShift CI script to download the latest odo from https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/latest rather than building the latest odo from main
Makes the script consistent with our github action (at least once https://github.com/devfile/api/issues/771 is fixed)
N/A
=> OpenShift CI: Download latest odo rather than building from main

stacks/nodejs-vue/devfile.yaml
Avoids the pesky permissions issues on OpenShift
=> Override Cypress Cache folder for nodejs-vue 

stacks/java-maven/devfile.yaml, stacks/java-openliberty-gradle/devfile.yaml, stacks/java-openliberty/devfile.yaml, stacks/java-quarkus/devfile.yaml, stacks/java-springboot/devfile.yaml, stacks/java-vertx/devfile.yaml, stacks/java-websphereliberty-gradle/devfile.yaml, stacks/java-websphereliberty/devfile.yaml, stacks/java-wildfly-bootable-jar/devfile.yaml, stacks/java-wildfly/devfile.yaml, stacks/python-django/devfile.yaml, stacks/python/devfile.yaml
Debug commands are using `DEBUG_PORT` variable but that variable is not defined in containers.
This was not an issue for `odo` as it automatically injects this variable if it is not defined, but this creates problems for other tools.
fixes one of the items in https://github.com/devfile/api/issues/679
=> add missing DEBUG_PORT env variable

stacks/java-websphereliberty-gradle/devfile.yaml, stacks/java-websphereliberty/devfile.yaml
Replace deprecated `/projects` with `${PROJECT_SOURCE}` 
https://github.com/devfile/api/issues/681
=> Replace hardcoded `/projects/` with `${PROJECT_SOURCE}`

.github/PULL_REQUEST_TEMPLATE.md, .gitignore, CONTRIBUTING.md
update the PR template to include an additional check in PR acceptance criteria to clarify the requirement to check on tools
Fixes https://github.com/devfile/api/issues/814
=> update the PR template to clarify the requirement on tools provider check

extraDevfileEntries.yaml
this pr adds go sample to devfile registry
Fixes https://github.com/devfile/api/issues/787
=> add go sample

.ci/openshift_integration.sh, .github/workflows/validate-devfiles-minikube.yaml
Don't use the odo v3-alpha binary. Stay on odo v2.x until the scripts are updated by the odo team to support odo v3.
=> Hardcode to odo v2.5.1 for tests

OWNERS, stacks/OWNERS, stacks/dotnet50/OWNERS, stacks/dotnet60/OWNERS, stacks/dotnetcore31/OWNERS, stacks/go/OWNERS, stacks/java-maven/OWNERS, stacks/java-openliberty-gradle/OWNERS, stacks/java-openliberty/OWNERS, stacks/java-quarkus/OWNERS, stacks/java-springboot/OWNERS, stacks/java-vertx/OWNERS, stacks/java-websphereliberty-gradle/OWNERS, stacks/java-websphereliberty/OWNERS, stacks/java-wildfly-bootable-jar/OWNERS, stacks/java-wildfly/OWNERS, stacks/nodejs-angular/OWNERS, stacks/nodejs-nextjs/OWNERS, stacks/nodejs-nuxtjs/OWNERS, stacks/nodejs-react/OWNERS, stacks/nodejs-svelte/OWNERS, stacks/nodejs-vue/OWNERS, stacks/nodejs/OWNERS, stacks/php-laravel/OWNERS, stacks/python-django/OWNERS, stacks/python/OWNERS
Signed-off-by: eyuen <eyuen@redhat.com>
Add default stack and tools review owners. No devfile/stack changes
[_Link to github issue(s)_](https://github.com/devfile/api/issues/807)
_Does any documentation need to be updated with your changes?_ No
Invites have been sent to the Devfile Reviewers group to provide read access which is required for the reviewer.
=> Add default stack and tools review owners

stacks/go/devfile.yaml, stacks/java-maven/devfile.yaml, stacks/java-quarkus/devfile.yaml, stacks/java-springboot/devfile.yaml, stacks/java-vertx/devfile.yaml, stacks/java-wildfly-bootable-jar/devfile.yaml, stacks/java-wildfly/devfile.yaml, stacks/nodejs/devfile.yaml, stacks/php-laravel/devfile.yaml, stacks/python-django/devfile.yaml, stacks/python/devfile.yaml
Updates all 2.0.0 devfiles to 2.1.0
This is because when trying to implement `variables` into the devfile,
it does not work with 2.0.0 and our `odo` implementaiton.
https://github.com/redhat-developer/odo/issues/5719
Signed-off-by: Charlie Drage <charlie@charliedrage.com>
=> Update the schema version to 2.1.0

extraDevfileEntries.yaml
this PR adds .NET 6.0 sample to the registry
HAS issue:https://issues.redhat.com/projects/DEVHAS/issues/DEVHAS-79?filter=allopenissues 
- [] Check Tools Provider
=> add dotnet6.0 sample

stacks/dotnet50/devfile.yaml, stacks/dotnet60/devfile.yaml, stacks/dotnetcore31/devfile.yaml, stacks/go/devfile.yaml, stacks/java-maven/devfile.yaml, stacks/java-openliberty-gradle/devfile.yaml, stacks/java-openliberty/devfile.yaml, stacks/java-quarkus/devfile.yaml, stacks/java-springboot/devfile.yaml, stacks/java-vertx/devfile.yaml, stacks/java-websphereliberty-gradle/devfile.yaml, stacks/java-websphereliberty/devfile.yaml, stacks/java-wildfly-bootable-jar/devfile.yaml, stacks/java-wildfly/devfile.yaml, stacks/nodejs-angular/devfile.yaml, stacks/nodejs-nextjs/devfile.yaml, stacks/nodejs-nuxtjs/devfile.yaml, stacks/nodejs-react/devfile.yaml, stacks/nodejs-svelte/devfile.yaml, stacks/nodejs-vue/devfile.yaml, stacks/nodejs/devfile.yaml, stacks/php-laravel/devfile.yaml, stacks/python-django/devfile.yaml, stacks/python/devfile.yaml
Signed-off-by: Paul Schultz <pschultz@pobox.com>
Fixed python debug issue and updated descriptions
Fixes https://github.com/devfile/api/issues/876
Fixes https://github.com/devfile/api/issues/883
=> Fixed python debug and updated descriptions

.ci/deploy/devfile-registry.yaml, .ci/deploy/route.yaml
Need to use template.openshift.io/v1 instead of v1 for OpenShift templates
=> Use proper API version for templates

stacks/java-quarkus/devfile.yaml, tests/check_non_terminating.sh
fixes https://github.com/devfile/api/issues/949
this PR also increases timeout for pulling images in `check_non_terminating.sh`, there was a few failures with `icr.io/appcafe/open-liberty-devfile-stack:22.0.0.1-gradle` image that were caused only because the image was not downloaded in time.
=> increase timeout in check_non_terminating tests and update image in java-quarkus to java 17

extraDevfileEntries.yaml, stacks/dotnet50/devfile.yaml, stacks/dotnet60/devfile.yaml, stacks/dotnetcore31/devfile.yaml, stacks/java-springboot/devfile.yaml
Reverted dotnet stack projectTypes to dotnet
related https://github.com/redhat-developer/odo/issues/6234
=> Reverts dotnet stack projectTypes to dotnet

tests/odov3/odo_test.go
updates odo v3 tests
- adds `odo dev` failure detection. Previously if `odo dev` failed, the test continued until it reached timeout. Now it `odo dev` failure is detected, and tests fail right after it happens. 
- adds `odo log` call and shows its output if tests failed to make it easier to debug failing tests
=> odo v3 tests: add `odo dev` failure detection

stacks/java-maven/devfile.yaml, stacks/java-openliberty-gradle/devfile.yaml, stacks/java-openliberty/devfile.yaml, stacks/java-quarkus/devfile.yaml, stacks/java-springboot/devfile.yaml, stacks/java-vertx/devfile.yaml, stacks/java-websphereliberty-gradle/devfile.yaml, stacks/java-websphereliberty/devfile.yaml, stacks/java-wildfly-bootable-jar/devfile.yaml, stacks/java-wildfly/devfile.yaml, stacks/nodejs/devfile.yaml, stacks/python-django/devfile.yaml, stacks/python/devfile.yaml, tests/check_odov2.sh, tests/odov3/odo_test.go
This adds missing debug endpoints in Devfiles where a debug command is declared and expected to be listening on the debug port (injected via the `DEBUG_PORT` environment variable).
This is required in tools like `odo`, so the endpoint can be detected and port-forwarded using `odo dev --debug`. See https://github.com/redhat-developer/odo/issues/5988
I've tested this in other tools like Dev Spaces, where I noticed that some of the Devfiles used there are already declaring such endpoints, e.g.: https://github.com/devspaces-samples/quarkus-quickstarts/blob/devspaces-3-rhel-8/devfile.yaml#L12-L15
Fixes https://github.com/redhat-developer/odo/issues/5988
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its …
=> Declare missing debug endpoints

.ci/Dockerfile
Signed-off-by: Michael Valdron <mvaldron@redhat.com>
This change is to temporarily disable updates from `devfile-index-base:next` built under [registry-support](https://github.com/devfile/registry-support) until deployment is ready for the new build process.
Image reference to `devfile-index-base` has been changed to stay on the current digest instead of using the image tag `next`.
part of devfile/api#747
_Have you tested the …
=> Halt updates from `devfile-index-base`

extraDevfileEntries.yaml
This is consistent with the other '.NET' items in the OpenShift catalog, and the other devfiles which also don't include a version number.
@kadel ptal.
=> Remove .NET version number from template.

stacks/java-maven/devfile.yaml, stacks/java-springboot/devfile.yaml
use registry.access.redhat.com/ubi8/openjdk-11:latest for java-maven and java-springboot stacks
It looks like the original image are not maintained anymore. Last update was more than 8 months ago (nightly tag), and they have Critical vulnerabilities (quay scanner shows 84 Critical-level vulnerabilities.)
=> use more up-to-date images for java-maven and java-springboot

stacks/nodejs/devfile.yaml
This adds the missing `DEBUG_PORT` environment variable to the Node.JS stack. Otherwise, the `debug` command won't start when used with the starter project declared in this stack.
See https://github.com/devfile/api/issues/929 for more details.
Fixes https://github.com/devfile/api/issues/929
I manually ran the …
=> Fix missing `DEBUG_PORT` environment variable in Node.JS stack

.ci/Dockerfile
quay.io/devfile/devfile-index-base:f16affcff745d534d19bc73d63e12bf8e2bf4d04 should work instead
=> Use different base image for dockerfile

.ci/deploy/devfile-registry.yaml, .ci/openshift_integration.sh
Adds necessary securityContext fields to the OpenShift template in order to run on OCP 4.12+
=> Add securityContexts for OCP 4.12

.ci/Dockerfile, .ci/build.sh, .ci/build_and_deploy.sh, .ci/deploy/devfile-registry.yaml, .ci/openshift_integration.sh, .gitignore
Updates provided to build scripts and community devfile registry OpenShift template file to support new registry viewer setup. No stacks or samples updated.
fixes devfile/api#747
=> Update build and deploy pipeline

.ci/deploy/devfile-registry.yaml
Signed-off-by: Michael Valdron <mvaldron@redhat.com>
Updates the probing in the OpenShift template to ensure the registry index server is ready before launching the registry viewer.
part of devfile/api#1019
=> Probe changes in OpenShift template

.github/workflows/validate-stacks.yaml, tests/check_non_terminating.sh, tests/check_odov2.sh
Signed-off-by: Michael Hoang <mhoang@redhat.com>
The github action (`actions-setup-minikube`) for setting up minikube currently uses `cri-dockerd v0.2.3` which contains a bug where large images won't download. This is fixed in `cri-dockerd v0.2.6` but hasn't been updated in the github action yet.
This workaround pre pulls images without a timeout.
fixes https://github.com/devfile/api/issues/987 …
=> pre pulling images for minikube tests

.ci/deploy/devfile-registry.yaml
Corrects the environment variable name for the analytics write key, `ANALYTICS_WRITE_KEY` to `NEXT_PUBLIC_ANALYTICS_WRITE_KEY`. This change should fix the broken telemetry.
fixes devfile/api#1006
=> Telemetry fix for community registry viewer deployment

.ci/deploy/devfile-registry.yaml
Blanks the analytics write key from the default value of the parameter in the OpenShift template. Since the analytics write key is now set on production deployment, there is no need to have the key set by default in the OpenShift template.
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test …
=> Blank registry viewer analytics write key in OpenShift template

.ci/deploy/devfile-registry.yaml
Adds missing required probes removed in devfile/api#1019.
Additional changes:
- Removes unnecessary port forward to registry viewer container
part of devfile/api#1040
=> Add liveness and readiness probes to registry viewer container in the OpenShift template

.ci/Dockerfile, .github/workflows/ci.yaml
Updates go version to 1.18 for ci due to changes from https://github.com/devfile/registry-support/pull/169
=> ci: updating go version to 1.18

.ci/Dockerfile
Updates image tag of the builder step under the [`Dockerfile`](https://github.com/devfile/registry/blob/5cda5e5156073a512373c4a738424cc349446b26/.ci/Dockerfile#L15) to use `registry.access.redhat.com/ubi8/go-toolset` due to the deployment environment's restriction, denying image pulls from Docker Hub.
fixes devfile/api#1083
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry …
=> Update builder image tag for CI

.ci/acceptance-tests/devfile-registry-acceptance.yaml
Adds environment variable required to the acceptance testing OpenShift template which enables the delay on testing to probe the target registry for readiness, a feature added in devfile/api#1086.
This ensures acceptance testing is perform *after* the staging deployment is ready.
fixes devfile/api#1095 …
=> Add probe timeout variable to acceptance testing template

tests/get_stacks.sh
Changes the git diff output that is used to get stacks changed for pr delta testing from this:
```
stacks/go/{1.0.2 => 1.1.0}/devfile.yaml               | 25 ++++++++++++++++++++++++-
stacks/go/{2.0.0 => 2.1.0}/devfile.yaml               | 25 ++++++++++++++++++++++++-
stacks/go/{2.0.0 => 2.1.0}/docker/Dockerfile          |  0
stacks/go/{2.0.0 => 2.1.0}/kubernetes/deploy.yaml     |  0
stacks/go/stack.yaml                                  |  4 ++--
tests/get_stacks.sh                                   |  2 +-
7 files changed, 51 insertions(+), 12 deletions(-)
```
to this:
```
stacks/go/1.1.0/devfile.yaml
stacks/go/2.1.0/devfile.yaml
stacks/go/2.1.0/docker/Dockerfile
stacks/go/2.1.0/kubernetes/deploy.yaml …
```
=> fix(ci): using name only flag for getting changed pr files

stacks/dotnet50/devfile.yaml, stacks/dotnet60/devfile.yaml, stacks/dotnetcore31/devfile.yaml
This PR is related to [alizer#135](https://github.com/redhat-developer/alizer/issues/135).
The 3 devfiles related to `.NET` have the same set of tags, and they are not explicitly mention their `.NET` framework. In case we add specific tags (e.g `.NET 5.0`), `alizer` should be able to pick the correct devfile. Right now, it finds 3 devfiles having the same list of tags and as a result it calculates the same weight for each one of them.
fixes https://github.com/devfile/api/issues/1087
_Have you tested the changes with …
=> Update dotnet tags to improve alizer devfile matching

stacks/python-django/devfile.yaml, stacks/python/2.1.0/devfile.yaml, stacks/python/3.0.0/devfile.yaml
This task is part of the devtools week. Updates the python image `registry.access.redhat.com/ubi9/python-39` from tag `1-108` to `1-122`.
=> [Devtools Week] Update python image tags

stacks/java-maven/devfile.yaml, stacks/java-quarkus/devfile.yaml, stacks/java-springboot/1.2.0/devfile.yaml, stacks/java-springboot/2.0.0/devfile.yaml, stacks/java-vertx/devfile.yaml
It specifies the tags for 3 different stacks:
- `java-maven` (from `registry.access.redhat.com/ubi8/openjdk-11:latest` to `registry.access.redhat.com/ubi8/openjdk-11:1.15`)
- `java-quarkus` (from `registry.access.redhat.com/ubi8/openjdk-17:latest` to `registry.access.redhat.com/ubi8/openjdk-17:1.15`)
- `java-springboot` (from `registry.access.redhat.com/ubi8/openjdk-11:latest` to `registry.access.redhat.com/ubi8/openjdk-11:1.15`)
Fixes https://github.com/devfile/api/issues/849
_Have you tested the changes with existing …
=> Fix tags for Java stack images

tests/check_non_terminating.sh
Removes the docker image being tested in the `check_non_terminating.sh` script after the container has been checked for termination.
This is needed because in the case where the list of images being tested is large (nightly runs or merging to main), the images are all downloaded to the Github runner and consumes all the disk space.
Removing the image after is has been marked as successful allows all the images to be tested in the same Github workflow run.
fixes https://github.com/devfile/api/issues/1135
_Have you tested the …
=> cleanup minikube docker image in non terminating test

tests/check_non_terminating.sh
Removes the docker image as per the merged PR https://github.com/devfile/registry/pull/189. Adds the `--force` flag because there is occasionally a conflict when trying to do the removal.
```shell
COMMAND: "minikube ssh docker image rm registry.access.redhat.com/ubi8/nodejs-18:1-47.1684740189"
Error response from daemon: conflict: unable to remove repository reference "registry.access.redhat.com/ubi8/nodejs-18:1-47.1684740189" (must force) - container 2e45242f9811 is using its referenced image f77092719a71
```
https://github.com/devfile/api/issues/1135
related pr: https://github.com/devfile/registry/pull/189
_Does this repository's tests …
=> use the force flag when removing minikube docker images

tests/check_rhtap_nightly.sh, tests/rhtap/rhtap_test.go
This Pr create namespace for each devfile. to avoid tekton bug. See discussion: https://redhat-internal.slack.com/archives/C04GVLR0155/p1692087863337849
=> Generate namespace for every devfile samples in RHTAP cluster

.ci/Dockerfile.offline, .ci/build.sh
Adds a dockerfile that packages resources and updates the devfiles to use the packaged resources.
https://github.com/devfile/api/issues/329
=> add dockerfile to support offline registry builds

CONTRIBUTING.md
After the merge of the [PR for the support of branches per version of devfile sample](https://github.com/devfile/registry-support/pull/178), it would be useful to add more information about this to the contributing guide.
Fixes https://github.com/devfile/api/issues/1209
=> Update contributing guide for sample multiple versions

.github/workflows/validate-stacks.yaml, tests/odov3/odo_test.go
/kind bug
This fixes the issue reported in https://github.com/devfile/api/issues/1103, where the `odo v3` tests would not run any tests on certain stacks.
The issue has been narrowed down to stacks that have no starter projects in their Devfiles, like [udi](https://github.com/devfile/registry/blob/main/stacks/udi/devfile.yaml).
This PR makes sure to test such stacks, by leveraging the [`odo dev --no-commands`](https://odo.dev/blog/odo-v3.12.0#full-control-over-the-application-lifecycle-with-odo-dev---no-commands-and-odo-run) command, to check that the Dev Session just starts properly.
Fixes https://github.com/devfile/api/issues/1103
_Does …
=> Make sure to run `odo` v3 tests for stacks that have no starter projects

renovate.json
This PR fixes the failure in the DCO check for renovate PRs. In order to do so, it extends the `:gitSignOff` preset of renovate configuration. You can check more info about the proposed workaround [here](https://docs.renovatebot.com/configuration-options/#commitbody)
fixes https://github.com/devfile/api/issues/1280
=> Extend gitSignOff

tests/odov3/odo_test.go, tests/odov3/types.go
This PR tries to copy all additional resources found inside a stack after `odo init --devfile-path`. This way we are able to use `odo init` in an empty directory and run `odo dev` with all the resources required.
fixes https://github.com/devfile/api/issues/1288
=> Copy additional stack resources inside tmpDir before validating stacks with odov3

stacks/java-springboot/1.3.0/devfile.yaml, stacks/java-springboot/2.1.0/devfile.yaml, stacks/java-springboot/2.1.0/docker/Dockerfile, stacks/java-springboot/2.1.0/kubernetes/deploy.yaml, stacks/java-springboot/stack.yaml
This updates the container image to `registry.access.redhat.com/ubi9/openjdk-17`, to keep up with the latest JDK LTS, security-wise.
Also JDK 17 is now a requirement for recent versions of Spring Boot.
&mdash;
Tested with `odo`.
=> [java-springboot] Use LTS JDK 17 image

stacks/java-quarkus/devfile.yaml
As it is mentioned in https://github.com/devfile/api/issues/1293 the checks of `odov3` and `odov2` are failing because we reach the memory limit of the container when we are trying to build the quarkus application.
I've managed to fix this issue by increasing the component memory limit to `1024Mi`.
fixes https://github.com/devfile/api/issues/1293
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) …
=> Increase java-quarkus container memory limit

.ci/build.sh, .ci/build_and_deploy.sh, README.md
This PR allows the use of podman as a container engine to run the build and deploy scripts.
resolves https://github.com/devfile/api/issues/1339
To run the scripts with `docker` you can run them normally with `bash .ci/build.sh` and `bash .ci/build_and_deploy.sh`. In order to test that podman support works first run `export USE_PODMAN=true` and then either `bash .ci/build.sh` or `bash .ci/build_and_deploy.sh`.
=> Add podman support for the build and deploy scripts

renovate.json
This PR simply overrides the configuration from the platform engineering bot here: https://github.com/platform-engineering-org/.github/blob/main/default.json#L19-L20 in order to disable `automerge` from the bot.
=> Disable automerge from renovate bot

stacks/go/1.3.0/devfile.yaml, stacks/go/2.3.0/devfile.yaml, stacks/go/2.3.0/docker/Dockerfile, stacks/go/2.3.0/kubernetes/deploy.yaml, stacks/go/stack.yaml
This adds a new stack that supports Go version 1.20.x. This is done by adding version `2.3.0`
resolves https://github.com/devfile/api/issues/1316
=> Create go 1.20 stack version

tests/rhtap/rhtap_test.go, tests/rhtap/types.go
After the merge of https://github.com/devfile/registry/pull/254 the `extraDevfilesEntries.yaml` now supports multiple sample versions. The `tests/rhtap/rhtap_test.go` test was using directly the `entry.Git.Remotes.Origin` and wasn't checking for existing sample versions.
As a result, this PR introduces an update to the `rhtap_test.go` where the `types.go` are updated to reflect the support of multiple sample version and upon testing to check for a default sample version instead of `entry.Git.Remotes`.
Fixes https://github.com/devfile/api/issues/1372
_Does any documentation need to be …
=> Add sample version support on rhtap nightly

renovate.json
This PR reverts all updates into the `renovate.json` file in order to prevent the bot from automerging the automatically created PRs in order to update the image tags used inside devfiles. Example PRs that have been automatically merged:
* https://github.com/devfile/registry/pull/261
* https://github.com/devfile/registry/pull/259
* https://github.com/devfile/registry/pull/260
In order to bring back the changes introduced here: https://github.com/devfile/registry/pull/240 we should confirm that the bot does not automerge the PRs.
N/A
_Does any documentation need to be updated with your …
=> Revert updates to renovate.json

tests/check_odov3.sh
This PR adds the `vertx-secured-http-example` in the list of skipped stacks of the `test/check_odov3.sh` test, following what has been done for the rest of the `vertx` starter projects. This can help to avoid having check failures for vert.x tests because of high demand of resources.
Example failure can be found here: https://github.com/devfile/registry/actions/runs/7250922945/job/19779089833
N/A …
=> Add vertx-secured-http-example in odov3 skipped starterprojects

renovate.json
Simply increases the `prConcurrentLimit` from 5 to 10. This will help us update more stack image versions per run and ensure that all stacks are checked once every two weeks.
N/A
=> Increase prConcurrentLimit to 10

renovate.json
This PR simply removes the `.devfile.yaml` file from the renovate checks.
N/A
=> Exclude root devfile from renovate checks

.github/workflows/validate-stacks.yaml
This PR adds a slack notification for the `validate-stacks` nightly run. More detailed if a run fails in any of the jobs github action will send a slack message to the referenced `SLACK_CHANNEL_ID`.
The message format has been defined in the related issue.
Fixes https://github.com/devfile/api/issues/1061
=> Add slack notification for validate checks run

stacks/udi/devfile.yaml
All recent [PRs](https://github.com/devfile/registry/pulls) for registry have failed for the following trace:
```
Error: failed to generate index struct: udi index component is not valid:
Devfile udi has broken or not existing icon
```
This PR simply adds the raw devfile icon image found inside the [devfile-web repo](https://raw.githubusercontent.com/devfile/devfile-web/main/apps/landing-page/public/pwa-192x192.png).
N/A
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry …
=> Fix devfile udi stack icon

tests/check_odov3.sh
Simply adds another `vert.x` starterproject as a skipped one following the same reasoning with https://github.com/devfile/registry/pull/264 and all other vert.x examples skipped in the past.
N/A
=> Add vertx-configmap-example to odo3 check's skipped starterprojects

.ci/build_and_deploy.sh, README.md
This PR enables the use of the `PLATFORM_EV` variable for users running `build_and_deploy.sh`. Due to a change made [here](https://github.com/devfile/devfile-web/commit/163464ed66bbf9354a1c683571360980cab4a3b9) on `devfile-web`, the build script requires the setting of `PLATFORM_EV` to run properly for users on arm64 architecture. In the devfile registry `build_and_deploy.sh` script it clones and runs build scripts from `devfile-web`. These would fail without this change.
fixes https://github.com/devfile/api/issues/1366 …
=> Add support for arm64 users to build scripts

.github/CODEOWNERS
Adds `CODEOWNERS` file referencing [Devfile Services Team](https://github.com/orgs/devfile/teams/devfile-services-team) to their owned community devfile registry stacks.
fixes devfile/api#1458
=> [DevTools] Add codeowners to devfile owned stacks

stacks/dotnet60/devfile.yaml
- update schema to the 2.2.0 (latest 2.2.2 is not yet supported - https://github.com/devfile/api/issues/1454)
- use 'https' protocol for .net 6.0 devfile
N/A
try it out on Developer Sandbox - https://workspaces.openshift.com/#https://raw.githubusercontent.com/devfile/registry/1f99545009bad5ab1f3231c66bcd6bf29d583573/stacks/ …
=> chore: use 'https' protocol for .net 6.0 devfile. Update schema to 2.2.0

.ci/Dockerfile, .ci/Dockerfile.offline
Freezes `devfile-index-base` at https://github.com/devfile/registry-support/commit/ffc3a09964b840b3d421dcf5d8d2afbf69322f64 until devfile/api#1473 is resolved to support Go 1.19 for the community registry.
This is needed to merge https://github.com/devfile/registry-support/pull/212 successfully.
**Important: Updates to the [registry viewer](https://github.com/devfile/devfile-web) or the stack/sample content will still apply to deployments.**
https://github.com/devfile/api/issues/1469
_Does …
=> Freeze `devfile-index-base` at `ffc3a09`

.ci/Dockerfile, .ci/Dockerfile.offline
Continuing from https://github.com/devfile/registry/pull/316, index/generator also needs to be frozen at an earlier state (such as `v1.1.0`) to fix failures due to use of Go 1.19 since https://github.com/devfile/registry-support/commit/3325cfe7a14ca95e245f4426c6731ce5667d2ed8. This fixed use of `v1.1.0` can be lifted once https://github.com/devfile/api/issues/1473 is resolved.
https://github.com/devfile/api/issues/1469
_Have you …
=> Freeze index/generator at `v1.1.0`

.ci/Dockerfile, .ci/Dockerfile.offline, .devfile.yaml, .github/workflows/ci.yaml, README.md, tests/README.md
First of the PRs that will be opened in order to complete https://github.com/devfile/api/issues/1473. This PR specifically updates the CI workflows and Dockerfiles to use `go 1.19`. This PR also adds a badge to the readme that visually shows that `go 1.19` is being implemented.
fixes https://github.com/devfile/api/issues/1473
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry …
=> update go version in ci and dockerfiles

stacks/java-wildfly/2.0.1/Containerfile, stacks/java-wildfly/2.0.1/deploy.yaml, stacks/java-wildfly/2.0.1/devfile.yaml, stacks/java-wildfly/stack.yaml
=> Wildfly 2.0.1

stacks/dotnet50/devfile.yaml
use 'https' protocol for .net 5.0 devfile. Update schema to 2.2.0
similar PR for .net 6.0 - https://github.com/devfile/registry/pull/298
try it out on Developer Sandbox - https://workspaces.openshift.com/#https://raw.githubusercontent.com/devfile/registry/dff9ad0e8c2ce5cc6de8e5d05b82e80bb1155bc0/st …
=> chore: use 'https' protocol for .net 5.0 devfile. Update schema to 2.2.0

extraDevfileEntries.yaml, stacks/nodejs/2.1.1/devfile.yaml, stacks/nodejs/2.2.0/devfile.yaml, stacks/nodejs/stack.yaml
Replaces the broken icon for `nodejs` stack with the one added in the `devfile-stack-icons` repo. 
Fixes https://github.com/devfile/api/issues/1484
=> Replace nodejs icon with devfile-stack-icons link

stacks/nodejs-svelte/1.2.1/devfile.yaml, stacks/nodejs-svelte/stack.yaml
Updates nodejs-svelte stack:
- Add new version 1.2.1
- Set https protocol for the endpoint
- Set 1.2.1 version as a default one
https://github.com/eclipse/che/issues/22869
Try it out on Developer Sandbox:
[![Contribute](https://www.eclipse.org/che/contribute.svg)](https://workspaces.openshift.com/#/https://raw.githubusercon …
=> Update nodejs-svelte stack

renovate.json, stacks/nodejs-angular/2.0.2/devfile.yaml, stacks/nodejs-angular/stack.yaml, stacks/nodejs-nextjs/1.0.3/devfile.yaml, stacks/nodejs-nextjs/stack.yaml, stacks/nodejs-nuxtjs/1.0.3/devfile.yaml, stacks/nodejs-nuxtjs/stack.yaml, stacks/nodejs-react/2.0.2/devfile.yaml, stacks/nodejs-react/stack.yaml, stacks/nodejs-svelte/1.0.3/devfile.yaml, stacks/nodejs-svelte/stack.yaml, stacks/nodejs-vue/1.0.2/devfile.yaml, stacks/nodejs-vue/stack.yaml, stacks/nodejs/2.1.1/devfile.yaml, stacks/nodejs/stack.yaml
This PR adds the `Deprecated` tag to stacks with the `Nodejs 16` image. It also adds these deprecated stacks to the `renovate.json` exclusion list and bumps the default version for all changed stacks up by 1 so the default version is not a deprecated stack.
fixes https://github.com/devfile/api/issues/1364 …
=> add deprecation to nodejs 16

tests/odov3/odo_test.go, tests/odov3/types.go
This PR disables temporarily (until the https://github.com/devfile/api/issues/1494 is completed) the `schemaVersions 2.2.1 & 2.2.2` . Once the related issue is completed this change should be reverted.
temporarily fixes https://github.com/devfile/api/issues/1494
=> TEMP ignore schemaVersions 2.2.2 and 2.2.1 due to odo incompatibility

stacks/php-laravel/2.0.1/devfile.yaml, stacks/php-laravel/stack.yaml
1. Created new version folder 2.0.1
2. Updated schema version to 2.2.2
3. Updated endpoint protocol to https
4. Set the default version to 2.0.1 in stack.yaml
=> Update php-laravel devfile

stacks/nodejs-nextjs/1.2.1/devfile.yaml, stacks/nodejs-nextjs/stack.yaml
Updates `nodejs-nextjs` stack:
- Add new version: `1.2.1`
- Set `schemaVersion: 2.2.2`
- Set `https` protocol for the endpoint
- Set `1.2.1` version as a default one
https://github.com/eclipse/che/issues/22869
You can use the following link to start a workspace for testing: …
=> Update nodejs-nextjs stack

stacks/nodejs-nuxtjs/1.2.1/devfile.yaml, stacks/nodejs-nuxtjs/stack.yaml
Updates `nodejs-nuxtjs` stack:
- Add new version: `1.2.1`
- Set `schemaVersion: 2.2.2`
- Set `https` protocol for the endpoint
- Set `1.2.1` version as a default one
https://github.com/eclipse/che/issues/22869
You can use the following link to start a workspace for testing: …
=> Update nodejs-nuxtjs stack

.github/workflows/validate-stacks.yaml, tests/check_odov2.sh, tests/check_odov3.sh, tests/odov3/odo_test.go
This PR fixes the nightly run failures occurring for the odo v2 and odo v3 tests. A summary of changes made are:
- Increased resources allocated to the Minikube instance to `14gb` and `4 cpus`, the allocated resources by default were far too low and could cause issues for some stacks.
- Excluded `java-quarkus` stack from testing as it is not running properly, even in local testing with `odo v2` and `odo v3` it was hanging and never finishing. An investigation issue will need to be opened for this stack.
- Increased `maxTries` from 20 to 50. This is used as a timer while ports are being forwarded, I noticed some java stacks were being timed out at 20 but needed anywhere from 24-50 tries to properly forward.
- Implemented …
=> Fix Nightly Run Failures

stacks/java-wildfly-bootable-jar/1.3.0/devfile.yaml, stacks/java-wildfly-bootable-jar/stack.yaml
Updates **java-wildfly-bootable-jar** stack:
Add new version 1.3.0
- Set **HTTPS** protocol for the endpoint
- Set the **1.3.0** version as the default one
https://github.com/eclipse/che/issues/22869
=> Update default version for java-wildfly-bootable-jar stack; set https protocol

stacks/java-wildfly/2.0.2/devfile.yaml, stacks/java-wildfly/stack.yaml
Avoid the Containerfile conflict between the one from the git repo and the one from the registry
[_Link to github issue(s)_](https://github.com/devfile/api/issues/1493)
=> Fixing small issues in WildFly 2.0.1

stacks/java-springboot/1.4.0/devfile.yaml, stacks/java-springboot/2.2.0/devfile.yaml, stacks/java-springboot/2.2.0/docker/Dockerfile, stacks/java-springboot/2.2.0/kubernetes/deploy.yaml, stacks/java-springboot/stack.yaml
Add a 2.2.2 devfile version and set https endpoint to Spring Boot stack.
1. Fix outdated "schemaVersion" attribute
2. Fix "Application is not available" error when launch Spring Boot application using Dev Spaces 3.12.0 / Eclipse Che Next"
_Note_: It was necessary to truncate the endpoint name to handle the maximum endpoint name length limitation of 15 characters. …
=> Add a 2.2.2 devfile version and set https endpoint to Spring Boot stack

tests/check_odov2.sh, tests/check_odov3.sh
This PR skips the `java-quarkus` stack entirely as it is failing our nightly run. Prior to this PR only the `community` starter was failing but now the entire stack is. An issue is going to be opened to investigate and fix the stack.
N/A
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test …
=> Update Nightly Run

stacks/java-quarkus/1.3.0/devfile.yaml, stacks/java-quarkus/1.3.1/devfile.yaml, stacks/java-quarkus/1.4.1/devfile.yaml, stacks/java-quarkus/stack.yaml
Explicitly set java version in the java-quarkus zip urls to java 17, in order to fix the error from the `init-compile` command:
```
INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 2 source files with javac [debug release 21] to target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.345 s
[INFO] Finished at: 2024-04-12T10:05:13Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project code-with-quarkus: Fatal error compiling: error: release version 21 not …
```
=> Explicitly set java version as a query parameter in the java-quarkus zip urls

.github/workflows/validate-stacks.yaml, stacks/go/2.3.0/devfile.yaml
Simply updates the `check_odo3.sh` check to use the [nightly builds of odo](https://odo.dev/docs/overview/installation/#nightly-builds) instead of 3.15.0
fixes https://github.com/devfile/api/issues/1415
=> Use odo nightly builds instead of 3.15.0

stacks/OWNERS
Thanks for adding me some years ago to review changes to the devfile registry. But I don't think I can help here regularly, and I never had.
I would be happy if the bot stopped requesting reviews from my side. Feel free to ping me in special cases on Slack or here, but I need to reduce notifications on GitHub a bit.
=> Update OWNERS (remove myself)

stacks/java-vertx/1.4.0/devfile.yaml, stacks/java-vertx/stack.yaml
Add a new version and set https endpoint to Java Vertx stack.
https://github.com/eclipse-che/che/issues/22869
=> Add new version and set https endpoint to java-vertx

.github/workflows/validate-samples.yaml, tests/README.md
Revised the cached samples path in https://github.com/devfile/registry/pull/397, missed the definition in the workflow which is causing current failures. Additional fix to documentation example.
=> Fix samples path in workflow

stacks/java-quarkus/1.3.1/devfile.yaml, stacks/java-quarkus/1.4.1/devfile.yaml
In order to fix the maven build in the java quarkus sample, modify the devfile commands with maven wrapper script instead of the pure `mvn` call, see: https://github.com/eclipse-che/che/issues/22961
fixes https://github.com/eclipse-che/che/issues/22961
fixes devfile/api#1541
=> Use maven wrapper script instead of the mvn in java-quarkus commands

.ci/Dockerfile, .ci/Dockerfile.offline, .ci/build-multi-arch.sh, .ci/build.sh, .github/workflows/ci.yaml, .github/workflows/pushimge-next.yaml, README.md
These changes allow for the devfile index image to be built for multiple architectures and pushed to quay.io. The changes are:
- Addition of `build-multi-arch.sh` that takes care of building and pushing the index image to quay, built for both `linux/amd64` and `linux/arm64`. It has the ability to build with either docker or podman.
- Updated `build.sh` to allow for an argument to be passed that allows the user to build for a different architecture.
- Updated `Dockerfile` and `Dockerfile.offline` to dynamically set the yq architecture.
- Updated documentation for new `build.sh` script.
- Updated github workflows to use the new scripts and build/push multi-arch to quay
fixes …
=> Multi Arch Image Building for Devfile Index

stacks/java-maven/1.3.1/devfile.yaml, stacks/java-maven/stack.yaml
- update schema to `2.2.2`;
- use `https` protocol for the `java-maven` devfile
https://github.com/eclipse-che/che/issues/22869
https://workspaces.openshift.com/#https://raw.githubusercontent.com/azatsarynnyy/registry/java-maven-u …
=> Update `Maven Java` stack

stacks/java-wildfly/2.0.0/devfile.yaml, stacks/java-wildfly/2.0.1/devfile.yaml, stacks/java-wildfly/2.0.2/devfile.yaml
Use same case for Java language in Wildfly stacks than others
it avoids having Java and java listed in tooling
for instance:
=> Use same case for Java language in Wildfly stacks than others

.ci/generate_last_mod_file.sh
This PR aims to fix the issue described in the linked issue below regarding stacks showing the default Go `time.Time` value. The `stack` and `version` vars in the generation script were flipped, resulting in the parsing from `index/generator` to not be able to find the resulting stacks and issuing the default date as a result.
fixes https://github.com/devfile/api/issues/1610
_Have you tested the changes with existing tools, i.e. …
=> Fix lastModified Filter

stacks/java-maven/1.3.0/devfile.yaml, stacks/java-maven/1.3.1/devfile.yaml, stacks/java-springboot/1.2.0/devfile.yaml, stacks/java-springboot/1.3.0/devfile.yaml, stacks/java-springboot/1.4.0/devfile.yaml, stacks/java-springboot/2.0.0/devfile.yaml, stacks/java-springboot/2.1.0/devfile.yaml, stacks/java-springboot/2.2.0/devfile.yaml, stacks/nodejs/2.1.1/devfile.yaml, stacks/nodejs/2.2.0/devfile.yaml, stacks/nodejs/2.2.1/devfile.yaml
This PR simply updates the `StarterProjects` for all versions of `java-springboot` and `nodejs` stacks. Those stacks were using starter projects from the [github.com/odo-devfiles](https://github.com/odo-devfiles) org. In order to move them to a better monitored org the PR makes the following changes:
* Replaces the https://github.com/odo-devfiles/springboot-ex starter project with its [fork](https://github.com/devfile-samples/springboot-ex) under devfile-samples.
* Replaces the https://github.com/odo-devfiles/nodejs-ex with the https://github.com/nodeshift-starters/devfile-sample.
The PR requires 3 approvals:
* @kadel as the owner of the `java-springboot` stack.
* @BethGriggs as the owner of the `nodejs` stack.
* @devfile/che-team as mentioned in the [registry stack PR review …
=> Replace starter projects from `odo-devfile` org

stacks/java-maven/1.2.0/devfile.yaml, stacks/java-maven/1.3.0/devfile.yaml, stacks/java-maven/1.3.1/devfile.yaml
https://catalog.redhat.com/software/containers/ubi9/openjdk-17/61ee7c26ed74b2ffb22b07f6?image=65a90783d59cca758b7d8d64&container-tabs=packages https://catalog.redhat.com/software/containers/ubi8/openjdk-11/5dd6a4b45a13461646f677f4?image=6639ed26fe2c35406921c084&container-tabs=packages …
=> Fix Maven version in description of Java Maven stack

stacks/java-quarkus/1.3.0/devfile.yaml, stacks/java-quarkus/1.3.1/devfile.yaml, stacks/java-quarkus/1.4.0/devfile.yaml, stacks/java-quarkus/1.4.1/devfile.yaml, stacks/java-quarkus/1.5.0/devfile.yaml
fixes devfile/api#1612
it is causing stacktraces:
```
tools: Could not load Logmanager "org.jboss.logmanager.LogManager"
tools: java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
tools:  at
org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
``` …
=> Remove LogManager property in Quarkus stacks (#1612)

stacks/java-springboot/stack.yaml
it was set to a previous version originally to use a schema version 2.1 but in fact the default version was already upgraded to 2.2 3 months ago https://github.com/devfile/registry/commit/db0c583c550b7b8bf5ef3f3afbb85ade165f0d8b
=> Use latest Java Spring Boot stack as default

.github/CODEOWNERS, stacks/dotnet80/devfile.yaml
Added `dotnet80` stack
https://github.com/devfile/api/issues/1540
=> Added dotnet80 stack

.ci/generate_last_mod_file.sh
This PR contains the changes required to the `generate_last_mod_file.sh` script to allow for the `last_modified.json` to properly contain stacks/samples that do not have a version. In the case of a non-versioned item the `version` field in the json will be `"null"`.
For samples the parsing handles the following 3 cases:
1. Versioned sample
2. Non-versioned sample that has a git branch preference (revision)
3. Non-versioned sample that has no git branch preference (defaults to main)
Example output:
```
{
"stacks": [
{
"name": "dotnet50",
"version": "1.0.4",
"lastModified": "2024-05-14T17:06:30+03:00"
},
{
"name": "dotnet60",
"version": "1.0.3",
"lastModified": "2024-07-22T15:33:17+02:00"
},
{
"name": "dotnetcore31", …
```
=> Update generation script to handle non-versioned items

stacks/java-quarkus/stack.yaml
Updates description of java-quarkus stack, because a [default version is 1.5.0](https://github.com/devfile/registry/blob/main/stacks/java-quarkus/stack.yaml#L11) and it uses OpenJDK 21 
https://github.com/eclipse-che/che/issues/23058
=> fix description of java-quarkus satck

tests/odov3/go.mod, tests/odov3/go.sum, tests/validate_devfile_schemas/go.mod, tests/validate_devfile_schemas/go.sum
This PR pulls in the newest devfile/library release, `v2.3.0`.
https://github.com/devfile/api/issues/1620
=> Update devfile/library version to v2.3.0

tests/check_odov3.sh
The ollama stack for the moment gets timeout error on registry nightly run. I'm opening the current PR as a temporary workaround. A permanent fix should be added in this issue: https://github.com/devfile/api/issues/1632
N/A
=> Skip ollama stack on nightly run

stacks/java-maven/1.3.0/devfile.yaml, stacks/java-maven/1.3.1/devfile.yaml, stacks/java-springboot/1.2.0/devfile.yaml, stacks/java-springboot/1.3.0/devfile.yaml, stacks/java-springboot/1.4.0/devfile.yaml, stacks/java-springboot/2.0.0/devfile.yaml, stacks/java-springboot/2.1.0/devfile.yaml, stacks/java-springboot/2.2.0/devfile.yaml
The PR reverts the update of the starterproject of `springboot` in several stacks. The previous attempt to update has been made in order to avoid using the `odo-devfiles` org but it seems that it has an impact (see https://github.com/devfile/api/issues/1628).
Fixes https://github.com/devfile/api/issues/1628
_Explain what …
=> Revert springboot starterproject update

stacks/java-maven/1.3.0/devfile.yaml, stacks/java-maven/1.3.1/devfile.yaml, stacks/java-springboot/1.2.0/devfile.yaml, stacks/java-springboot/1.3.0/devfile.yaml, stacks/java-springboot/1.4.0/devfile.yaml, stacks/java-springboot/2.0.0/devfile.yaml, stacks/java-springboot/2.1.0/devfile.yaml, stacks/java-springboot/2.2.0/devfile.yaml
This PR reverts the commit a55e8501a70dd97e2e4895de19f2732df8194c42. The commit was originally merged in attempt to fix https://github.com/devfile/api/issues/1628. As the issue still occurs post merge might be good to revert the updates and keep using the `devfile-sample-java-springboot` as the starter project.
N/A …
=> Revert "Revert springboot starterproject update (#476)"

stacks/java-springboot/stack.yaml
This reverts commit 0513d066ac5f48a0729cd7fe330222df6a4fa2bd.
Temporary fix by reverting the update of the default version for the springboot stack. The reasoning is shared here: https://github.com/devfile/api/issues/1628#issuecomment-2329776908
Fixes https://github.com/devfile/api/issues/1628
_Explain what tests you …
=> Revert "Use latest Java Spring Boot stack as default (#439)"

.tekton/devfile-registry-push.yaml
Adds `next` as an additional tag to the on-push tekton task.
First portion of https://github.com/devfile/api/issues/1636
_Explain what tests you personally ran to ensure the changes are …
=> Add next tag to tekton on-push

.ci/deploy/devfile-registry.yaml
Use a separate parameter to use a different tag for the registry-viewer component.
Part of https://github.com/devfile/api/issues/1657
_Explain what tests you personally ran to ensure the changes …
=> Add separate registry viewer tag parameter to OpenShift deployment template

.ci/openshift_integration.sh, tests/check_odov2.sh, tests/check_odov3.sh, tests/odov3/odo_test.go
To fix the current unexpected integration testing failures this PR changes include the following:
- Adds TLS verification enablement feature for the odo test scripts and openshift integration test script. This is to address the failing PR integration testing check due to the self signed cert not being accepted by `curl` when testing stacks using HTTPS rather than HTTP.
- Migrates integration test script to use the odo v3 test script instead of odo v2 test script. This resolves failures due to some of the community stacks using newer schema versions for the default stack versions than what the odo v2 client supports.
fixes devfile/api#1663
fixes devfile/api#1664 …
=> Fix PR integration testing

.ci/openshift_integration.sh, .tekton/devfile-registry-main-pull-request.yaml, .tekton/devfile-registry-main-push.yaml, stacks/jhipster-online/2.33.0/devfile.yaml, tests/check_odov2.sh, tests/check_odov3.sh, tests/odov3/odo_test.go
Migrate jhipster online to red hat developer demo repo and image to quay devfile organization
GitHub
https://github.com/redhat-developer-demos/jhipster-online
Quay
https://quay.io/repository/devfile/jhipster-online
[_Link the GitHub/GitLab/JIRA issues that are related to this PR._](https://github.com/eclipse-che/che-website/pull/112#issuecomment-2561319046)
_Instructions for the reviewer on how to test your changes._
Taking a look at the [Video Demo](https://www.youtube.com/watch?v=b7xbcTAGNIQ)
=> update: migrate jhipster online to red hat developer demo

renovate.json
This PR migrates the old renovate config to one that works with Konflux. In order to meet the needs of MintMaker Renovate via Konflux as well as the Konflux patch updates, the following changes have been made:
- Include `tekton` under `enabledManagers`
- Increase run schedule for renovate to avoid Enterprise Contract failures due to out of date Konflux image references
fixes https://github.com/devfile/api/issues/1667
_Does any documentation need to be updated …
=> chore(konflux): Migrate renovate configuration

renovate.json
Creates a schedule for Konflux patching to happen every Tuesday and Thursday after 9pm, schedule specified in #553, restores default renovate schedule for other devfile registry patching to every 2nd and 4th Thursday after 9pm.
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTI …
=> Create Konflux patching renovate schedule

stacks/jhipster-online/2.33.0/devfile.yaml, stacks/jhipster-online/2.33.1/devfile.yaml, stacks/jhipster-online/stack.yaml, tests/check_odov3.sh
Added new devfile 2.33.1 with the next updates:
- Update JHipster Core: jhipster 8.8.0
Added Blueprints:
- generator-jhipster-micronau 3.6.0
- generator-jhipster-quarkus 3.4.0
- generator-jhipster-dotnetcore 4.2.0
Upgrade jhipster udi image.
- quay.io/devfile/jhipster-online@sha256:1d34f067a20d87d7cfa5e304fef23556f865656dfa1c01cb8501ea078a03157e
Example Try with Quarkus Generator:
Modify cmd key jhipster by jhipster-quarkus from application section:
```
application:
tmp-folder: /tmp
jhipster-cmd:
#cmd: jhipster
cmd: jhipster-quarkus
```
Modify url-pipeline key by url-pipeline quarkus example:
```
openshift:
devspace:
url-devfile: https://raw.githubusercontent.com/redhat-developer-demos/jhipster-online/main/src/main/kubernetes/jhipster-devspaces.yaml
tekton:
url-pipeline: …
```
=> Upgrade JHipster Online Stack

.tekton/devfile-registry-main-pull-request.yaml, .tekton/devfile-registry-main-push.yaml
Based on the description and the resources provided in https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/conforma/new-sast-tasks-mar25.md
The PR updates the shell and unicode cheks to use the checks that the onliner installs. Provided here: https://github.com/simonbaird/konflux-pipeline-patcher/blob/main/specific-one-liners.md#sast-unicode-and-shell-check-tasks
Fixes https://github.com/devfile/api/issues/1702 (partially)
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile …
=> Fix unicode and shell sast checks

stacks/udi/devfile.yaml
This PR updates image that is used in UDI stack. 
**quay.io/devfile/universal-developer-image:ubi8-latest** is not supported anymore, it was replaced by UBI9 based image. 
For more details check https://github.com/eclipse-che/che/issues/23034.
https://github.com/eclipse-che/che/issues/23034
Tested on Eclipse Che
Workspace should start from the udi/devfile.yaml
=> chore: upgrade udi/devfile to use UBI9 based image

.github/CODEOWNERS, stacks/nodejs-mongodb/devfile.yaml
In the registry I don't see any stack that provides a component with data base. So, this pull request introduces a devfile with two components:
**Node.js Application**: A component to develop and run a simple Node.js web application.
**Mongo Database**: A component to run MongoDB, which the Node.js app will connect to for data storage.
The project sample also includes the necessary deployment configurations, enabling the easy deployment of both the Node.js app and MongoDB to a K8S cluster.
This setup will allow developers to quickly start working on a full-stack application with a working MongoDB instance, all within a K8S environment. The configurations and components are designed to streamline development and deployment in K8S.
https://github.com/eclipse-che/che/issues/23351
_Have you …
=> feat: Add devfile with Node.js web app and MongoDB components

.ci/Dockerfile, .ci/Dockerfile.offline, .devfile.yaml, .github/workflows/ci.yaml, .github/workflows/pushimge-next.yaml, .github/workflows/validate-samples.yaml, .github/workflows/validate-stacks.yaml, README.md, tests/check_non_terminating/go.mod, tests/odov3/go.mod, tests/validate_devfile_schemas/go.mod
Bumps up the tests of the registry to go version 1.23 as that the UBI8 go-toolset has no tag on 1.24 only 1.23.
See: https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1
Additionally, as shared by the odo team the odo nightly builds are no longer supported, thus the current PR uses the newest version of odo (3.16.1) which includes the support for devfile versions 2.2.1 & 2.2.2
Fixes https://github.com/devfile/api/issues/1697
Fixes https://github.com/devfile/api/issues/1714
_Have you tested …
=> Bump up registry go version to 1.23 and odo to 3.16.1

.github/CODEOWNERS, stacks/kaoto/devfile.yaml, tests/check_odov3.sh
added kaoto project
How to test? (OpenShift DevSpaces)
[![Open](https://img.shields.io/static/v1?label=Open%20in&message=Developer%20Sandbox&logo=eclipseche&color=FDB940&labelColor=525C86)](https://workspaces.openshift.com/#https://github.com/maximilianoPizarro/kaoto/tree/feature/devfile?storageType=ephemeral)
From your Workspaces started, run the tasks from devfile, confirm the port to expose and open in browser:
optional: podman mode
Only run "tasks start-with-docker"
=> add kaoto project

stacks/go/1.4.0/devfile.yaml, stacks/go/stack.yaml
Cuts new stack version for Go stack that provides 1.24 Go version.
_Explain what tests you personally ran to ensure the changes are functioning as expected._
_Instructions for the reviewer on how to test your changes._
_Any notes you would like to include for the reviewer._
=> Go 1.24 for 1.x stack version
